/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2023-11-06 01:33:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.cinema;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class cinema_002dhomepage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>cinema-homepage</title>\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"/movieInsight/resources/css/cinema/cinema-homepage.css\">\r\n");
      out.write("   <link\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("      href=\"https://cdn.jsdelivr.net/npm/swiper@10/swiper-bundle.min.css\"\r\n");
      out.write("    />\r\n");
      out.write("     <script src=\"https://cdn.jsdelivr.net/npm/swiper@10/swiper-bundle.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("\r\n");
      out.write("       \r\n");
      out.write("    <!-- <div id=\"sortButton\">\r\n");
      out.write("\r\n");
      out.write("        <button onclick=\"sortKoreanLinks()\" style=\"margin: 50px 0 0 100px;  \r\n");
      out.write("            border-radius: 10px;\">&nbsp;한글순&nbsp;</button>\r\n");
      out.write("\r\n");
      out.write("        <button onclick=\"sortDistance()\" style=\"margin: 10px 0 0 10px;  \r\n");
      out.write("            border-radius: 10px;\">&nbsp;거리순&nbsp;</button>\r\n");
      out.write("\r\n");
      out.write("        <button  style=\"margin: 10px 0 0 10px;  \r\n");
      out.write("            border-radius: 10px;\"> &nbsp;시설 만족도&nbsp; </button>\r\n");
      out.write("\r\n");
      out.write("        <button  style=\"margin: 10px 0 0 10px;  \r\n");
      out.write("            border-radius: 10px;\"> &nbsp;직원 친절도&nbsp; </button>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("   -->\r\n");
      out.write("\r\n");
      out.write("    <div class=\"cinema_list_container\">\r\n");
      out.write("\r\n");
      out.write("       \r\n");
      out.write("\r\n");
      out.write("        <section class=\"cinema_list swiper main-1\">\r\n");
      out.write("\r\n");
      out.write("                \r\n");
      out.write("            <ul class=\"swiper-wrapper\">\r\n");
      out.write("              \r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"swiper-button-prev main-1-p\"></div>\r\n");
      out.write("            <div class=\"swiper-button-next main-1-n\"></div>\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("   \r\n");
      out.write("    <!--영화 이동 링크-->\r\n");
      out.write("    <a href=\"/movieInsight/movie\">\r\n");
      out.write("        <img  class=\"movie_link\"><br>\r\n");
      out.write("    </a>\r\n");
      out.write("\r\n");
      out.write("    <!--지도-->\r\n");
      out.write("    <div style=\"position:relative; width:70%; height: 500px; display:flex; margin-left:25%; margin-top:1%;\">\r\n");
      out.write("	    <div class=\"map_wrap\">\r\n");
      out.write("	        <div id=\"map\" style=\"position:absolute; width:100%; height:100% ; overflow:hidden;\"></div>\r\n");
      out.write("	\r\n");
      out.write("	        <div id=\"menu_wrap\" class=\"bg_white\">\r\n");
      out.write("	            <div class=\"option\">\r\n");
      out.write("	                <div>\r\n");
      out.write("	                    <form onsubmit=\"searchPlaces(); return false;\">\r\n");
      out.write("	                        키워드 : <input type=\"text\" value=\"cgv\" id=\"keyword\" size=\"10\"> \r\n");
      out.write("	                        <button type=\"submit\" style=\"color:black\";>검색하기</button> \r\n");
      out.write("	                    </form>\r\n");
      out.write("	                </div>\r\n");
      out.write("	            </div>\r\n");
      out.write("	            <hr>\r\n");
      out.write("	            <ul id=\"placesList\"></ul>\r\n");
      out.write("	            <div id=\"pagination\"></div>\r\n");
      out.write("	        </div>\r\n");
      out.write("	    </div>\r\n");
      out.write("    </div>           \r\n");
      out.write("    \r\n");
      out.write("    <div class=\"cinema_promotion\">\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${promotion.promotionURL}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"cinema_special\" id=\"cinema_special\" target=\"_blank\">\r\n");
      out.write("            <img src=\"/movieInsight/resources/images/cinema/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${promotion.promotionImg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"promotionImg\">\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"\" class=\"cinema_special\" target=\"_blank\">\r\n");
      out.write("            <li>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${promotion.promotionType}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</li> <br>\r\n");
      out.write("            <li>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${promotion.promotionContent}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</li> \r\n");
      out.write("        </a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <div id=\"cinema_promotion\">\r\n");
      out.write("        <div class=\"event_promotion\">\r\n");
      out.write("\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${event.eventURL}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"  class=\"preview_img\"  target=\"_blank\">\r\n");
      out.write("                <img src=\"/movieInsight/resources/images/cinema/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${event.eventImg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"eventImg\">\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${event.eventURL}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"  class=\"preview_text\" target=\"_blank\">\r\n");
      out.write("\r\n");
      out.write("                &lt;");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${event.eventTitle}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&gt; <br>\r\n");
      out.write("                <li>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${event.eventContent}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</li>\r\n");
      out.write("\r\n");
      out.write("            </a>\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <br><br><br><br><br>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=bd0095e2bd371f5a6ae43c67546f3c62&libraries=services\"></script>\r\n");
      out.write("<script src=\"/movieInsight/resources/js/cinema/cinema-homepage.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
